spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver  #mysql6 的驱动类
      url: jdbc:mysql://132.232.54.105:3306/xjc?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: 123456
      type: com.alibaba.druid.pool.DruidDataSource
      druid:
        max-wait: 60000
        max-active: 20
        min-idle: 5
        initial-size: 5
  thymeleaf:   #thymelea模板配置
      cache: false
      suffix: .html
      mode: LEGACYHTML5
      encoding: UTF-8
      servlet:
        content-type: text/html
      prefix: classpath:/templates/views/

  mvc:
    static-path-pattern: /static/**  #静态资源访问  等同于WebMvcConfig.addResourceHandlers()
#  resources:
#    static-locations: classpath:/static/ #@{}表示的是调用静态资源那一块，也就是你设置的spring.resources.static-locations=classpath:/static/这里面的内容

# mybatis
mybatis:
    mapper-locations: classpath*:com/xjc/mapper/**/*.xml # mapper.xml文件所在位置
    type-aliases-package: com.xjc.entity.*         #对应实体类的包名
    configuration:
      map-underscore-to-camel-case: true  #配置驼峰命名转换 在进行sql查询和初始化实体时mybatis会为我们自动转化
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #mybatis 控制台打印sql

#pagehelper分页插件
pagehelper:
  elperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql